In [1]:
from pyprojroot.here import here
import pandas as pd
import numpy as np

enterprise_df = pd.read_csv(here("data/raw/uad/enterprise_uad.csv"))
fha_df = pd.read_csv(here("data/raw/uad/fha_uad.csv"))

In [2]:
enterprise_df.info()
fha_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481868 entries, 0 to 1481867
Data columns (total 40 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   record_id               1481868 non-null  int64
 1   year                    1481868 non-null  int64
 2   weight                  1481868 non-null  int64
 3   state_fips_2010         1377644 non-null  float64
 4   state_fips_2020         104224 non-null   float64
 5   county_fips_2010        1376686 non-null  float64
 6   county_fips_2020        104207 non-null   float64
 7   tract_fips_2010         1357804 non-null  float64
 8   tract_fips_2020         102742 non-null   float64
 9   purpose                 1481868 non-null  int64
 10  owner_occupied          1481868 non-null  int64
 11  contract_price          746237 non-null   float64
 12  built_up                1481868 non-null  int64
 13  growth_rate             1481868 non-null  int64
 14  property_value_trend    1481868 non-null  int64
 15  demand_supply           1481868 non-null  int64
 16  marketing_time          1481868 non-null  int64
 17  sales_range_high        1354062 non-null  float64
 18  sales_range_low         1351084 non-null  float64
 19  updated_last_15_years   1481868 non-null  int64
 20  lot_size                1481868 non-null  int64
 21  quality                 1481868 non-null  int64
 22  condition               1481868 non-null  int64
 23  bathrooms               1481868 non-null  int64
 24  bedrooms                1481868 non-null  int64
 25  gross_living_area       1481868 non-null  int64
 26  median_adjustment       1481842 non-null  float64
 27  average_adjustment      1481842 non-null  float64
 28  adjusted_price          1481805 non-null  float64
 29  number_comparables      1481868 non-null  int64
 30  same_tract_percent      1471865 non-null  float64
 31  calculated_proximity    1475704 non-null  float64
 32  reported_proximity      1480808 non-null  float64
 33  value_sale_comparison   1481831 non-null  float64
 34  value_cost              1084631 non-null  float64
 35  value_income            34210 non-null    float64
 36  appraised_value         1481868 non-null  int64
 37  appraisal_to_contract   746237 non-null   float64
 38  comparison_to_contract  746213 non-null   float64
 39  dts_rural               1481868 non-null  int64
dtypes: float64(20), int64(20)
memory usage: 452.2 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266474 entries, 0 to 266473
Data columns (total 39 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   record_id               266474 non-null  int64
 1   year                    266474 non-null  int64
 2   weight                  266474 non-null  int64
 3   state_fips_2010         229385 non-null  float64
 4   state_fips_2020         37089 non-null   float64
 5   county_fips_2010        228987 non-null  float64
 6   county_fips_2020        37020 non-null   float64
 7   tract_fips_2010         189601 non-null  float64
 8   tract_fips_2020         27641 non-null   float64
 9   purpose                 266474 non-null  int64
 10  owner_occupied          266474 non-null  int64
 11  contract_price          209649 non-null  float64
 12  built_up                266474 non-null  int64
 13  growth_rate             266474 non-null  int64
 14  property_value_trend    266474 non-null  int64
 15  demand_supply           266474 non-null  int64
 16  marketing_time          266474 non-null  int64
 17  sales_range_high        234744 non-null  float64
 18  sales_range_low         234312 non-null  float64
 19  updated_last_15_years   266474 non-null  int64
 20  lot_size                266474 non-null  int64
 21  quality                 266474 non-null  int64
 22  condition               266474 non-null  int64
 23  bathrooms               266474 non-null  int64
 24  bedrooms                266474 non-null  int64
 25  gross_living_area       266474 non-null  int64
 26  median_adjustment       266398 non-null  float64
 27  average_adjustment      266398 non-null  float64
 28  adjusted_price          266287 non-null  float64
 29  number_comparables      266474 non-null  int64
 30  same_tract_percent      252140 non-null  float64
 31  calculated_proximity    252630 non-null  float64
 32  reported_proximity      266396 non-null  float64
 33  value_sale_comparison   259130 non-null  float64
 34  value_cost              196946 non-null  float64
 35  value_income            1933 non-null    float64
 36  appraised_value         259265 non-null  float64
 37  appraisal_to_contract   204130 non-null  float64
 38  comparison_to_contract  204071 non-null  float64
dtypes: float64(21), int64(18)
memory usage: 79.3 MB

In [3]:
enterprise_summary_df = pd.DataFrame({
    'Total Rows': len(enterprise_df),
    'Type': enterprise_df.dtypes,
    'Count of NaN': enterprise_df.isna().sum(),
    'Percent Null': round((enterprise_df.isna().sum()/len(enterprise_df))*100,2)
})

print(f"Summary of Enterprise Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)")
print(enterprise_summary_df)

Summary of Enterprise Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)
                        Total Rows     Type  Count of NaN  Percent Null
record_id                  1481868    int64             0          0.00
year                       1481868    int64             0          0.00
weight                     1481868    int64             0          0.00
state_fips_2010            1481868  float64        104224          7.03
state_fips_2020            1481868  float64       1377644         92.97
county_fips_2010           1481868  float64        105182          7.10
county_fips_2020           1481868  float64       1377661         92.97
tract_fips_2010            1481868  float64        124064          8.37
tract_fips_2020            1481868  float64       1379126         93.07
purpose                    1481868    int64             0          0.00
owner_occupied             1481868    int64             0          0.00
contract_price             1481868  float64        735631         49.64
built_up                   1481868    int64             0          0.00
growth_rate                1481868    int64             0          0.00
property_value_trend       1481868    int64             0          0.00
demand_supply              1481868    int64             0          0.00
marketing_time             1481868    int64             0          0.00
sales_range_high           1481868  float64        127806          8.62
sales_range_low            1481868  float64        130784          8.83
updated_last_15_years      1481868    int64             0          0.00
lot_size                   1481868    int64             0          0.00
quality                    1481868    int64             0          0.00
condition                  1481868    int64             0          0.00
bathrooms                  1481868    int64             0          0.00
bedrooms                   1481868    int64             0          0.00
gross_living_area          1481868    int64             0          0.00
median_adjustment          1481868  float64            26          0.00
average_adjustment         1481868  float64            26          0.00
adjusted_price             1481868  float64            63          0.00
number_comparables         1481868    int64             0          0.00
same_tract_percent         1481868  float64         10003          0.68
calculated_proximity       1481868  float64          6164          0.42
reported_proximity         1481868  float64          1060          0.07
value_sale_comparison      1481868  float64            37          0.00
value_cost                 1481868  float64        397237         26.81
value_income               1481868  float64       1447658         97.69
appraised_value            1481868    int64             0          0.00
appraisal_to_contract      1481868  float64        735631         49.64
comparison_to_contract     1481868  float64        735655         49.64
dts_rural                  1481868    int64             0          0.00

In [4]:
fha_summary_df = pd.DataFrame({
    'Total Rows': len(fha_df),
    'Type': fha_df.dtypes,
    'Count of NaN': fha_df.isna().sum(),
    'Percent Null': round((fha_df.isna().sum()/len(fha_df))*100,2)
})

print(f"Summary of FHA Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)")
print(fha_summary_df)

Summary of FHA Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)
                        Total Rows     Type  Count of NaN  Percent Null
record_id                   266474    int64             0          0.00
year                        266474    int64             0          0.00
weight                      266474    int64             0          0.00
state_fips_2010             266474  float64         37089         13.92
state_fips_2020             266474  float64        229385         86.08
county_fips_2010            266474  float64         37487         14.07
county_fips_2020            266474  float64        229454         86.11
tract_fips_2010             266474  float64         76873         28.85
tract_fips_2020             266474  float64        238833         89.63
purpose                     266474    int64             0          0.00
owner_occupied              266474    int64             0          0.00
contract_price              266474  float64         56825         21.32
built_up                    266474    int64             0          0.00
growth_rate                 266474    int64             0          0.00
property_value_trend        266474    int64             0          0.00
demand_supply               266474    int64             0          0.00
marketing_time              266474    int64             0          0.00
sales_range_high            266474  float64         31730         11.91
sales_range_low             266474  float64         32162         12.07
updated_last_15_years       266474    int64             0          0.00
lot_size                    266474    int64             0          0.00
quality                     266474    int64             0          0.00
condition                   266474    int64             0          0.00
bathrooms                   266474    int64             0          0.00
bedrooms                    266474    int64             0          0.00
gross_living_area           266474    int64             0          0.00
median_adjustment           266474  float64            76          0.03
average_adjustment          266474  float64            76          0.03
adjusted_price              266474  float64           187          0.07
number_comparables          266474    int64             0          0.00
same_tract_percent          266474  float64         14334          5.38
calculated_proximity        266474  float64         13844          5.20
reported_proximity          266474  float64            78          0.03
value_sale_comparison       266474  float64          7344          2.76
value_cost                  266474  float64         69528         26.09
value_income                266474  float64        264541         99.27
appraised_value             266474  float64          7209          2.71
appraisal_to_contract       266474  float64         62344         23.40
comparison_to_contract      266474  float64         62403         23.42

In [5]:
keep_cols = ["record_id",
             "year",
             "state_fips_2010",
             "county_fips_2010",
             "tract_fips_2010",
             "state_fips_2020",
             "county_fips_2020",
             "tract_fips_2020",
             "purpose",
             "owner_occupied",
             "contract_price",
             "lot_size",
             "quality",
             "condition",
             "bathrooms",
             "bedrooms",
             "gross_living_area",
             "appraised_value",
             "appraisal_to_contract"
            ]

enterprise_clean = enterprise_df[keep_cols].copy()
fha_clean = fha_df[keep_cols].copy()

In [6]:
# Convert to nullable integers
# 2010
enterprise_clean['state_fips_2010'] = enterprise_clean['state_fips_2010'].astype('Int64')
enterprise_clean['county_fips_2010'] = enterprise_clean['county_fips_2010'].astype('Int64')
enterprise_clean['tract_fips_2010'] = enterprise_clean['tract_fips_2010'].astype('Int64')
# 2020
enterprise_clean['state_fips_2020'] = enterprise_clean['state_fips_2020'].astype('Int64')
enterprise_clean['county_fips_2020'] = enterprise_clean['county_fips_2020'].astype('Int64')
enterprise_clean['tract_fips_2020'] = enterprise_clean['tract_fips_2020'].astype('Int64')

# Pad to correct digits, keep NaN as NaN
# 2010
enterprise_clean['state_fips_2010_clean'] = enterprise_clean['state_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(2)
enterprise_clean['county_fips_2010_clean'] = enterprise_clean['county_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(5)
enterprise_clean['tract_fips_2010_clean'] = enterprise_clean['tract_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(11)
# 2020
enterprise_clean['state_fips_2020_clean'] = enterprise_clean['state_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(2)
enterprise_clean['county_fips_2020_clean'] = enterprise_clean['county_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(5)
enterprise_clean['tract_fips_2020_clean'] = enterprise_clean['tract_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(11)

# Convert to nullable integers
# 2010
fha_clean['state_fips_2010'] = fha_clean['state_fips_2010'].astype('Int64')
fha_clean['county_fips_2010'] = fha_clean['county_fips_2010'].astype('Int64')
fha_clean['tract_fips_2010'] = fha_clean['tract_fips_2010'].astype('Int64')
# 2020
fha_clean['state_fips_2020'] = fha_clean['state_fips_2020'].astype('Int64')
fha_clean['county_fips_2020'] = fha_clean['county_fips_2020'].astype('Int64')
fha_clean['tract_fips_2020'] = fha_clean['tract_fips_2020'].astype('Int64')

# Pad to correct digits, keep NaN as NaN
# 2010
fha_clean['state_fips_2010_clean'] = fha_clean['state_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(2)
fha_clean['county_fips_2010_clean'] = fha_clean['county_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(5)
fha_clean['tract_fips_2010_clean'] = fha_clean['tract_fips_2010'].astype(str).replace('<NA>', np.nan).str.zfill(11)
# 2020
fha_clean['state_fips_2020_clean'] = fha_clean['state_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(2)
fha_clean['county_fips_2020_clean'] = fha_clean['county_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(5)
fha_clean['tract_fips_2020_clean'] = fha_clean['tract_fips_2020'].astype(str).replace('<NA>', np.nan).str.zfill(11)

In [7]:
enterprise_clean["state_fips"] = np.where(enterprise_clean["year"] == 2022, enterprise_clean["state_fips_2020_clean"], enterprise_clean["state_fips_2010_clean"])
enterprise_clean["state_fips"] = enterprise_clean["state_fips"].astype("string")
enterprise_clean["county_fips"] = np.where(enterprise_clean["year"] == 2022, enterprise_clean["county_fips_2020_clean"], enterprise_clean["county_fips_2010_clean"])
enterprise_clean["county_fips"] = enterprise_clean["county_fips"].astype("string")
enterprise_clean["tract_fips"] = np.where(enterprise_clean["year"] == 2022, enterprise_clean["tract_fips_2020_clean"], enterprise_clean["tract_fips_2010_clean"])
enterprise_clean["tract_fips"] = enterprise_clean["tract_fips"].astype("string")

fha_clean["state_fips"] = np.where(fha_clean["year"] == 2022, fha_clean["state_fips_2020_clean"], fha_clean["state_fips_2010_clean"])
fha_clean["state_fips"] = fha_clean["state_fips"].astype("string")
fha_clean["county_fips"] = np.where(fha_clean["year"] == 2022, fha_clean["county_fips_2020_clean"], fha_clean["county_fips_2010_clean"])
fha_clean["county_fips"] = fha_clean["county_fips"].astype("string")
fha_clean["tract_fips"] = np.where(fha_clean["year"] == 2022, fha_clean["tract_fips_2020_clean"], fha_clean["tract_fips_2010_clean"])
fha_clean["tract_fips"] = fha_clean["tract_fips"].astype("string")

In [8]:
enterprise_clean

,record_id,year,state_fips_2010,county_fips_2010,tract_fips_2010,state_fips_2020,county_fips_2020,tract_fips_2020,purpose,owner_occupied,...,appraisal_to_contract,state_fips_2010_clean,county_fips_2010_clean,tract_fips_2010_clean,state_fips_2020_clean,county_fips_2020_clean,tract_fips_2020_clean,state_fips,county_fips,tract_fips
0,1600123026000,2016,25,25017,25017360200,<NA>,<NA>,<NA>,2,1,...,NaN,25,25017,25017360200,NaN,NaN,NaN,25,25017,25017360200
1,2100277002000,2021,47,47157,47157020820,<NA>,<NA>,<NA>,1,2,...,107.3,47,47157,47157020820,NaN,NaN,NaN,47,47157,47157020820
2,1300187770000,2013,39,39145,39145003700,<NA>,<NA>,<NA>,2,1,...,NaN,39,39145,39145003700,NaN,NaN,NaN,39,39145,39145003700
3,1300185773000,2013,36,36029,36029009104,<NA>,<NA>,<NA>,1,2,...,102.6,36,36029,36029009104,NaN,NaN,NaN,36,36029,36029009104
4,1300045673000,2013,26,26103,26103002800,<NA>,<NA>,<NA>,1,2,...,101.3,26,26103,26103002800,NaN,NaN,NaN,26,26103,26103002800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481863,2200035244000,2022,<NA>,<NA>,<NA>,55,55071,55071000400,1,2,...,102.6,NaN,NaN,NaN,55,55071,55071000400,55,55071,55071000400
1481864,2200195295000,2022,<NA>,<NA>,<NA>,39,39023,39023001400,1,2,...,101.7,NaN,NaN,NaN,39,39023,39023001400,39,39023,39023001400
1481865,2200155857000,2022,<NA>,<NA>,<NA>,31,31055,31055007310,1,2,...,102.1,NaN,NaN,NaN,31,31055,31055007310,31,31055,31055007310
1481866,2200027013000,2022,<NA>,<NA>,<NA>,8,8035,8035014407,1,2,...,100.4,NaN,NaN,NaN,08,08035,08035014407,08,08035,08035014407
1481867,2200006825000,2022,<NA>,<NA>,<NA>,41,41017,41017000602,2,1,...,NaN,NaN,NaN,NaN,41,41017,41017000602,41,41017,41017000602

In [9]:
enterprise_clean.loc[enterprise_clean["purpose"] == 9, "purpose"] = np.nan
enterprise_clean.loc[enterprise_clean["owner_occupied"] == 9, "owner_occupied"] = np.nan
enterprise_clean.loc[enterprise_clean["lot_size"] == 9, "lot_size"] = np.nan
enterprise_clean.loc[enterprise_clean["quality"] == 9, "quality"] = np.nan
enterprise_clean.loc[enterprise_clean["condition"] == 9, "condition"] = np.nan
enterprise_clean.loc[enterprise_clean["bathrooms"] == 9, "bathrooms"] = np.nan
enterprise_clean.loc[enterprise_clean["bedrooms"] == 9, "bedrooms"] = np.nan
enterprise_clean.loc[enterprise_clean["gross_living_area"] == 9, "gross_living_area"] = np.nan

In [10]:
fha_clean.loc[fha_clean["purpose"] == 9, "purpose"] = np.nan
fha_clean.loc[fha_clean["owner_occupied"] == 9, "owner_occupied"] = np.nan
fha_clean.loc[fha_clean["lot_size"] == 9, "lot_size"] = np.nan
fha_clean.loc[fha_clean["quality"] == 9, "quality"] = np.nan
fha_clean.loc[fha_clean["condition"] == 9, "condition"] = np.nan
fha_clean.loc[fha_clean["bathrooms"] == 9, "bathrooms"] = np.nan
fha_clean.loc[fha_clean["bedrooms"] == 9, "bedrooms"] = np.nan
fha_clean.loc[fha_clean["gross_living_area"] == 9, "gross_living_area"] = np.nan

In [11]:
enterprise_clean["lot_size"] = pd.Categorical(
    enterprise_clean["lot_size"], categories=[1, 2, 3, 4, 5], ordered=True
)

enterprise_clean["quality"] = pd.Categorical(
    enterprise_clean["quality"], categories=[1, 2, 3, 4, 5], ordered=True
)

enterprise_clean["condition"] = pd.Categorical(
    enterprise_clean["condition"], categories=[1, 2, 3, 4, 5], ordered=True
)

enterprise_clean["bathrooms"] = pd.Categorical(
    enterprise_clean["bathrooms"], categories=[1, 2, 3, 4], ordered=True
)

enterprise_clean["bedrooms"] = pd.Categorical(
    enterprise_clean["bedrooms"], categories=[1, 2, 3], ordered=True
)

enterprise_clean["gross_living_area"] = pd.Categorical(
    enterprise_clean["gross_living_area"], categories=[1, 2, 3, 4, 5, 6, 7, 8], ordered=True
)

fha_clean["lot_size"] = pd.Categorical(
    fha_clean["lot_size"], categories=[1, 2, 3, 4, 5], ordered=True
)

fha_clean["quality"] = pd.Categorical(
    fha_clean["quality"], categories=[1, 2, 3, 4, 5], ordered=True
)

fha_clean["condition"] = pd.Categorical(
    fha_clean["condition"], categories=[1, 2, 3, 4, 5], ordered=True
)

fha_clean["bathrooms"] = pd.Categorical(
    fha_clean["bathrooms"], categories=[1, 2, 3, 4], ordered=True
)

fha_clean["bedrooms"] = pd.Categorical(
    fha_clean["bedrooms"], categories=[1, 2, 3], ordered=True
)

fha_clean["gross_living_area"] = pd.Categorical(
    fha_clean["gross_living_area"], categories=[1, 2, 3, 4, 5, 6, 7, 8], ordered=True
)

In [12]:
enterprise_clean["purpose"] = enterprise_clean["purpose"].astype("category")
enterprise_clean["owner_occupied"] = enterprise_clean["owner_occupied"].astype("category")

fha_clean["purpose"] = fha_clean["purpose"].astype("category")
fha_clean["owner_occupied"] = fha_clean["owner_occupied"].astype("category")

In [13]:
enterprise_clean["purchase"] = np.where(enterprise_clean["purpose"] == 1, True, False)
fha_clean["purchase"] = np.where(fha_clean["purpose"] == 1, True, False)

In [14]:
enterprise_clean.record_id.is_unique

True

In [15]:
fha_clean.record_id.is_unique

True

In [16]:
enterprise_clean["program"] = "enterprise"
fha_clean["program"] = "fha"

In [17]:
enterprise_clean["purchase"] = np.select(
    [enterprise_clean["purpose"].isna(), enterprise_clean["purpose"] == 1],
    [np.nan, True],
    default=False,
)
fha_clean["purchase"] = np.select(
    [fha_clean["purpose"].isna(), fha_clean["purpose"] == 1],
    [np.nan, True],
    default=False,
)

df_clean = pd.concat([enterprise_clean, fha_clean], ignore_index=True)

In [18]:
df_clean

,record_id,year,purpose,owner_occupied,contract_price,lot_size,quality,condition,bathrooms,bedrooms,gross_living_area,appraised_value,appraisal_to_contract,state_fips,county_fips,tract_fips,purchase,program
0,1600123026000,2016,2.0,1.0,NaN,5,4,3,4,3,8,1105000.0,NaN,25,25017,25017360200,False,enterprise
1,2100277002000,2021,1.0,2.0,305000.0,3,3,3,4,3,8,325000.0,107.3,47,47157,47157020820,True,enterprise
2,1300187770000,2013,2.0,1.0,NaN,2,4,4,2,3,5,195000.0,NaN,39,39145,39145003700,False,enterprise
3,1300185773000,2013,1.0,2.0,115000.0,2,3,4,2,2,4,125000.0,102.6,36,36029,36029009104,True,enterprise
4,1300045673000,2013,1.0,2.0,115000.0,2,5,4,1,2,2,115000.0,101.3,26,26103,26103002800,True,enterprise
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748337,2200038045000,2022,1.0,2.0,175000.0,4,4,3,2,2,5,175000.0,100.0,36,36057,<NA>,True,fha
1748338,2200028455000,2022,1.0,2.0,255000.0,2,4,4,2,1,1,255000.0,102.0,12,12031,<NA>,True,fha
1748339,2200021887000,2022,2.0,1.0,NaN,1,4,3,3,3,7,725000.0,NaN,06,06065,<NA>,False,fha
1748340,2200011492000,2022,1.0,2.0,505000.0,1,4,4,2,2,2,505000.0,100.6,06,06067,<NA>,True,fha
1748341,2200041167000,2022,2.0,1.0,NaN,NaN,4,3,NaN,2,1,NaN,NaN,18,18039,<NA>,False,fha

In [19]:
clean_summary = pd.DataFrame({
    'Total Rows': len(df_clean),
    'Type': df_clean.dtypes,
    'Count of NaN': df_clean.isna().sum(),
    'Percent Null': round((df_clean.isna().sum()/len(df_clean))*100,2)
})

print(f"Summary of Final Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)")
print(clean_summary)

Summary of Final Uniform Appraisal Dataset (UAD) Appraisal-Level Public Use File (PUF)
                       Total Rows            Type  Count of NaN  Percent Null
record_id                 1748342           int64             0          0.00
year                      1748342           int64             0          0.00
purpose                   1748342        category           341          0.02
owner_occupied            1748342        category           335          0.02
contract_price            1748342         float64        792456         45.33
lot_size                  1748342        category          9717          0.56
quality                   1748342        category            32          0.00
condition                 1748342        category            24          0.00
bathrooms                 1748342        category          7757          0.44
bedrooms                  1748342        category          1101          0.06
gross_living_area         1748342        category           333          0.02
appraised_value           1748342         float64          7209          0.41
appraisal_to_contract     1748342         float64        797975         45.64
state_fips                1748342  string[python]             0          0.00
county_fips               1748342  string[python]          1442          0.08
tract_fips                1748342  string[python]         70554          4.04
purchase                  1748342            bool             0          0.00
program                   1748342          object             0          0.00